spring.application.name=search-stock-api
server.port=8090

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5000}

baseUrl=https://brapi.dev/api/quote/
stockUrl=?range=5d&interval=1d&fundamental=true&dividends=false&token=dm5Q62W9vhrM82bqq9SywZ

apiKey=${API_KEY}